import {
  AccountPermissionGroup,
  AccountStore,
  AccountUser,
  PosBootstrap,
  DeviceConfig,
  PosLocalSettings,
  MemberProfile,
} from "@/lib/types";

export const defaultAccountStores: AccountStore[] = [
  {
    id: "macau-store-a",
    name: "澳門店 A",
    active: true,
    createdAt: "2026-08-08T00:00:00.000Z",
    updatedAt: "2026-08-08T00:00:00.000Z",
    note: "預設主門店。",
  },
  {
    id: "macau-store-b",
    name: "澳門店 B",
    active: true,
    createdAt: "2026-08-08T00:00:00.000Z",
    updatedAt: "2026-08-08T00:00:00.000Z",
    note: "分店示例。",
  },
];

export const defaultPermissionGroups: AccountPermissionGroup[] = [
  {
    id: "perm-admin",
    code: "admin-full",
    name: "管理員全權",
    role: "admin",
    permissions: { refundOrder: true, voidItem: true, manageAccounts: true },
    createdAt: "2026-08-08T00:00:00.000Z",
    updatedAt: "2026-08-08T00:00:00.000Z",
    note: "可管理帳戶、退款、退菜。",
  },
  {
    id: "perm-manager",
    code: "store-manager",
    name: "店長權限",
    role: "manager",
    permissions: { refundOrder: true, voidItem: true, manageAccounts: false },
    createdAt: "2026-08-08T00:00:00.000Z",
    updatedAt: "2026-08-08T00:00:00.000Z",
    note: "可退款、退菜，不可管理帳戶。",
  },
  {
    id: "perm-cashier",
    code: "cashier-basic",
    name: "收銀權限",
    role: "cashier",
    permissions: { refundOrder: false, voidItem: false, manageAccounts: false },
    createdAt: "2026-08-08T00:00:00.000Z",
    updatedAt: "2026-08-08T00:00:00.000Z",
    note: "基本收銀權限。",
  },
];

export const defaultAccountUsers: AccountUser[] = [
  {
    id: "acct-admin-1",
    account: "60000000",
    pin: "0000",
    name: "系統管理員",
    role: "admin",
    active: true,
    storeIds: ["macau-store-a", "macau-store-b"],
    permissionGroupId: "perm-admin",
    permissions: {
      refundOrder: true,
      voidItem: true,
      manageAccounts: true,
    },
    createdAt: "2026-08-08T00:00:00.000Z",
    updatedAt: "2026-08-08T00:00:00.000Z",
    note: "總管理帳戶，可管理所有帳戶狀態。",
  },
  {
    id: "acct-manager-1",
    account: "63936541",
    pin: "1234",
    name: "店長",
    role: "manager",
    active: true,
    storeIds: ["macau-store-a"],
    permissionGroupId: "perm-manager",
    permissions: {
      refundOrder: true,
      voidItem: true,
      manageAccounts: false,
    },
    createdAt: "2026-08-08T00:00:00.000Z",
    updatedAt: "2026-08-08T00:00:00.000Z",
    note: "門店管理帳戶。",
  },
  {
    id: "acct-cashier-1",
    account: "63936542",
    pin: "1234",
    name: "收銀員",
    role: "cashier",
    active: true,
    storeIds: ["macau-store-a"],
    permissionGroupId: "perm-cashier",
    permissions: {
      refundOrder: false,
      voidItem: false,
      manageAccounts: false,
    },
    createdAt: "2026-08-08T00:00:00.000Z",
    updatedAt: "2026-08-08T00:00:00.000Z",
    note: "前台收銀帳戶。",
  },
];

export const mockBootstrap: PosBootstrap = {
  sourceVersion: 1,
  storeId: "macau-store-a",
  storeName: "澳門店 A",
  currency: "MOP",
  categories: [
    { id: "cat-rice", name: "飯類" },
    { id: "cat-noodle", name: "粉麵" },
    { id: "cat-drink", name: "飲品" },
  ],
  menuItems: [
    {
      id: "item-bbq-rice",
      categoryId: "cat-rice",
      name: "叉燒飯",
      price: 48,
      printerGroup: "kitchen",
    },
    {
      id: "item-beef-noodle",
      categoryId: "cat-noodle",
      name: "牛腩麵",
      price: 52,
      printerGroup: "kitchen",
    },
    {
      id: "item-fish-pot",
      categoryId: "cat-rice",
      name: "酸菜魚",
      price: 138,
      printerGroup: "kitchen",
      specGroups: [
        {
          id: "spice",
          name: "辣度",
          selectionMode: "single",
          required: true,
          options: [
            { id: "mild", label: "小辣", priceDelta: 0 },
            { id: "medium", label: "中辣", priceDelta: 0 },
            { id: "hot", label: "大辣", priceDelta: 0 },
          ],
        },
        {
          id: "size",
          name: "份量",
          selectionMode: "single",
          required: true,
          options: [
            { id: "small", label: "小份", priceDelta: 0 },
            { id: "large", label: "大份", priceDelta: 20 },
          ],
        },
        {
          id: "addon",
          name: "配菜",
          selectionMode: "multi",
          required: false,
          options: [
            { id: "regular", label: "標準", priceDelta: 0 },
            { id: "tofu", label: "加豆腐", priceDelta: 8 },
            { id: "vermicelli", label: "加粉絲", priceDelta: 10 },
          ],
        },
      ],
    },
    {
      id: "item-toast",
      categoryId: "cat-rice",
      name: "餐蛋治",
      price: 28,
      printerGroup: "kitchen",
    },
    {
      id: "item-lemon-tea",
      categoryId: "cat-drink",
      name: "凍檸茶",
      price: 18,
      printerGroup: "drinks",
    },
    {
      id: "item-milk-tea",
      categoryId: "cat-drink",
      name: "凍奶茶",
      price: 20,
      printerGroup: "drinks",
    },
  ],
  tables: [
    { id: "table-a01", name: "A01", area: "1樓", floorId: "floor-1" },
    { id: "table-a02", name: "A02", area: "1樓", floorId: "floor-1" },
    { id: "table-b01", name: "B01", area: "1樓", floorId: "floor-1" },
    { id: "table-b02", name: "B02", area: "2樓", floorId: "floor-2" },
  ],
  rules: {
    orderFlow: "send_then_pay",
    allowSplitBill: false,
    allowMemberLookup: false,
    taxRate: 0,
    serviceChargeRate: 0,
    paymentMethods: ["cash", "card", "mpay"],
  },
  printerGroups: ["kitchen", "drinks", "receipt"],
  lastUpdatedAt: "2026-08-04T00:00:00.000Z",
};

export const defaultDeviceConfig: DeviceConfig = {
  deviceId: "tablet-01",
  terminalName: "收銀機 01",
  storeId: "macau-store-a",
  updatedAt: "2026-08-04T00:00:00.000Z",
  printers: [
    {
      id: "printer-kitchen-1",
      role: "zone",
      zoneId: "kitchen",
      connectionType: "lan",
      name: "廚房打印機",
      model: "EPSON TM-U220",
      paperSize: "80mm",
      ipAddress: "192.168.1.110",
      enabled: true,
    },
    {
      id: "printer-drinks-1",
      role: "zone",
      zoneId: "drinks",
      connectionType: "lan",
      name: "吧台打印機",
      model: "EPSON TM-T82X",
      paperSize: "80mm",
      ipAddress: "192.168.1.111",
      enabled: true,
    },
    {
      id: "printer-receipt-1",
      role: "receipt",
      connectionType: "usb",
      name: "收據打印機",
      model: "EPSON TM-T82X",
      paperSize: "80mm",
      usbLabel: "USB-Receipt-01",
      enabled: true,
    },
    {
      id: "printer-label-1",
      role: "label",
      zoneId: "drinks",
      connectionType: "usb",
      name: "杯貼標籤機",
      model: "Brother QL-820NWB",
      paperSize: "62mm",
      usbLabel: "USB-Label-01",
      enabled: false,
    },
  ],
};

export const defaultPosLocalSettings: PosLocalSettings = {
  floors: [
    {
      id: "floor-1",
      name: "1樓",
      tables: [
        { id: "table-a01", name: "A01", area: "1樓", floorId: "floor-1" },
        { id: "table-a02", name: "A02", area: "1樓", floorId: "floor-1" },
        { id: "table-a03", name: "A03", area: "1樓", floorId: "floor-1" },
      ],
    },
    {
      id: "floor-2",
      name: "2樓",
      tables: [
        { id: "table-b01", name: "B01", area: "2樓", floorId: "floor-2" },
        { id: "table-b02", name: "B02", area: "2樓", floorId: "floor-2" },
      ],
    },
  ],
  paymentMethods: ["現金", "Mpay", "中銀"],
  menuPrinterOverrides: {
    "item-bbq-rice": "kitchen",
    "item-beef-noodle": "kitchen",
    "item-fish-pot": "kitchen",
    "item-toast": "kitchen",
    "item-lemon-tea": "drinks",
    "item-milk-tea": "drinks",
  },
  printZones: [
    { id: "kitchen", name: "廚房" },
    { id: "drinks", name: "水吧" },
  ],
  specTemplates: [
    {
      id: "tpl-drink-default",
      name: "飲品通用規格",
      specGroups: [
        {
          id: "drink-size",
          name: "杯型",
          selectionMode: "single",
          required: true,
          options: [
            { id: "regular", label: "標準", priceDelta: 0 },
            { id: "large", label: "大杯", priceDelta: 2 },
          ],
        },
        {
          id: "drink-ice",
          name: "冰量",
          selectionMode: "single",
          required: true,
          options: [
            { id: "normal-ice", label: "正常冰", priceDelta: 0 },
            { id: "less-ice", label: "少冰", priceDelta: 0 },
            { id: "no-ice", label: "走冰", priceDelta: 0 },
          ],
        },
        {
          id: "drink-sugar",
          name: "甜度",
          selectionMode: "single",
          required: true,
          options: [
            { id: "full-sugar", label: "正常甜", priceDelta: 0 },
            { id: "half-sugar", label: "半糖", priceDelta: 0 },
            { id: "less-sugar", label: "少甜", priceDelta: 0 },
            { id: "no-sugar", label: "走甜", priceDelta: 0 },
          ],
        },
      ],
    },
  ],
  printTemplates: {
    receipt: {
      showRuler: true,
      snapToGrid: true,
      canvas: {
        width: 280,
        height: 560,
        zoom: 1,
      },
      sectionStyles: {
        store_name: { fontSize: 16, fontWeight: 700, textAlign: "center", padding: 4, textColor: "#0f172a", borderColor: "#fdba74", backgroundColor: "#fff7ed" },
        order_no: { fontSize: 12, fontWeight: 600, textAlign: "left", padding: 4, textColor: "#0f172a", borderColor: "#fdba74", backgroundColor: "#fff7ed" },
        table_name: { fontSize: 12, fontWeight: 500, textAlign: "left", padding: 4, textColor: "#0f172a", borderColor: "#fdba74", backgroundColor: "#fff7ed" },
        items: { fontSize: 11, fontWeight: 500, textAlign: "left", padding: 4, textColor: "#334155", borderColor: "#fdba74", backgroundColor: "#fff7ed" },
        total: { fontSize: 14, fontWeight: 700, textAlign: "right", padding: 4, textColor: "#7c2d12", borderColor: "#fdba74", backgroundColor: "#fff7ed" },
        payment_method: { fontSize: 11, fontWeight: 500, textAlign: "left", padding: 4, textColor: "#0f172a", borderColor: "#fdba74", backgroundColor: "#fff7ed" },
        order_note: { fontSize: 11, fontWeight: 500, textAlign: "left", padding: 4, textColor: "#0f172a", borderColor: "#fdba74", backgroundColor: "#fff7ed" },
        footer: { fontSize: 10, fontWeight: 500, textAlign: "center", padding: 4, textColor: "#475569", borderColor: "#fdba74", backgroundColor: "#fff7ed" },
      },
      sectionLayouts: {
        store_name: { x: 12, y: 16, width: 256, height: 40 },
        order_no: { x: 12, y: 60, width: 256, height: 40 },
        table_name: { x: 12, y: 104, width: 256, height: 40 },
        items: { x: 12, y: 152, width: 256, height: 190 },
        total: { x: 12, y: 350, width: 256, height: 46 },
        payment_method: { x: 12, y: 402, width: 256, height: 40 },
        order_note: { x: 12, y: 448, width: 256, height: 46 },
        footer: { x: 12, y: 500, width: 256, height: 38 },
      },
      sectionOrder: ["store_name", "order_no", "table_name", "items", "total", "payment_method", "order_note", "footer"],
      showStoreName: true,
      showOrderNo: true,
      showTableName: true,
      showPaymentMethod: true,
      showOrderNote: true,
      footerText: "多謝惠顧，歡迎再次光臨",
    },
    label: {
      showRuler: true,
      snapToGrid: true,
      canvas: {
        width: 360,
        height: 260,
        zoom: 1,
      },
      sectionStyles: {
        header: { fontSize: 14, fontWeight: 700, textAlign: "center", padding: 4, textColor: "#0f172a", borderColor: "#7dd3fc", backgroundColor: "#f0f9ff" },
        item_name: { fontSize: 16, fontWeight: 700, textAlign: "left", padding: 4, textColor: "#0f172a", borderColor: "#7dd3fc", backgroundColor: "#f0f9ff" },
        temperature: { fontSize: 12, fontWeight: 600, textAlign: "center", padding: 4, textColor: "#0f172a", borderColor: "#7dd3fc", backgroundColor: "#f0f9ff" },
        cup_type: { fontSize: 12, fontWeight: 600, textAlign: "center", padding: 4, textColor: "#0f172a", borderColor: "#7dd3fc", backgroundColor: "#f0f9ff" },
        sugar: { fontSize: 12, fontWeight: 600, textAlign: "center", padding: 4, textColor: "#0f172a", borderColor: "#7dd3fc", backgroundColor: "#f0f9ff" },
        ice: { fontSize: 12, fontWeight: 600, textAlign: "center", padding: 4, textColor: "#0f172a", borderColor: "#7dd3fc", backgroundColor: "#f0f9ff" },
        sugar_tag: { fontSize: 11, fontWeight: 600, textAlign: "center", padding: 4, textColor: "#0369a1", borderColor: "#7dd3fc", backgroundColor: "#f0f9ff" },
        ice_tag: { fontSize: 11, fontWeight: 600, textAlign: "center", padding: 4, textColor: "#0369a1", borderColor: "#7dd3fc", backgroundColor: "#f0f9ff" },
        addons: { fontSize: 11, fontWeight: 500, textAlign: "left", padding: 4, textColor: "#334155", borderColor: "#7dd3fc", backgroundColor: "#f0f9ff" },
        specs: { fontSize: 10, fontWeight: 500, textAlign: "left", padding: 4, textColor: "#475569", borderColor: "#7dd3fc", backgroundColor: "#f0f9ff" },
        item_note: { fontSize: 10, fontWeight: 500, textAlign: "left", padding: 4, textColor: "#475569", borderColor: "#7dd3fc", backgroundColor: "#f0f9ff" },
        order_no: { fontSize: 10, fontWeight: 600, textAlign: "center", padding: 4, textColor: "#0f172a", borderColor: "#7dd3fc", backgroundColor: "#f0f9ff" },
        footer: { fontSize: 10, fontWeight: 500, textAlign: "center", padding: 4, textColor: "#475569", borderColor: "#7dd3fc", backgroundColor: "#f0f9ff" },
      },
      sectionLayouts: {
        header: { x: 12, y: 12, width: 336, height: 28 },
        item_name: { x: 12, y: 46, width: 180, height: 42 },
        temperature: { x: 204, y: 46, width: 144, height: 34 },
        cup_type: { x: 12, y: 94, width: 108, height: 32 },
        sugar: { x: 126, y: 94, width: 108, height: 32 },
        ice: { x: 240, y: 94, width: 108, height: 32 },
        sugar_tag: { x: 12, y: 132, width: 108, height: 32 },
        ice_tag: { x: 126, y: 132, width: 108, height: 32 },
        addons: { x: 240, y: 132, width: 108, height: 48 },
        specs: { x: 12, y: 186, width: 336, height: 34 },
        item_note: { x: 12, y: 226, width: 180, height: 26 },
        order_no: { x: 198, y: 226, width: 84, height: 26 },
        footer: { x: 288, y: 226, width: 60, height: 26 },
      },
      sectionOrder: [
        "header",
        "item_name",
        "temperature",
        "cup_type",
        "sugar",
        "ice",
        "sugar_tag",
        "ice_tag",
        "addons",
        "specs",
        "item_note",
        "order_no",
        "footer",
      ],
      showOrderNo: true,
      showSpecs: true,
      showItemNote: true,
      headerText: "飲品標籤",
      footerText: "請盡快出品",
    },
  },
  notePresets: ["多飯", "少飯", "小冰", "少冰", "走冰", "少甜", "走甜", "走蔥", "走辣"],
  cancelNotePresets: ["客人取消", "售罄", "下錯單", "重開一單"],
  fullVoidBehavior: "cancelled",
  dineInQuickActionOrder: ["checkout", "view_order", "send_kitchen", "prints", "online_orders", "shift", "settings", "back_tables"],
  onlineOrderSettings: {
    autoAccept: false,
  },
};

export const defaultMembers: MemberProfile[] = [
  {
    id: "mem-001",
    name: "陳小明",
    phone: "66112233",
    balance: 320,
    level: "金卡",
    coupons: [
      {
        id: "cp-001",
        title: "滿100減20",
        type: "amount_off",
        amountOff: 20,
        minSpend: 100,
        stackable: false,
        expiresAt: "2026-12-31T23:59:59.000Z",
      },
      {
        id: "cp-002",
        title: "95折（最多減30）",
        type: "percent_off",
        percentOff: 5,
        maxOff: 30,
        minSpend: 50,
        stackable: false,
        expiresAt: "2026-12-31T23:59:59.000Z",
      },
    ],
  },
  {
    id: "mem-002",
    name: "李小姐",
    phone: "66334455",
    balance: 58,
    level: "銀卡",
    coupons: [
      {
        id: "cp-010",
        title: "滿50減10",
        type: "amount_off",
        amountOff: 10,
        minSpend: 50,
        stackable: true,
        expiresAt: "2026-12-31T23:59:59.000Z",
      },
      {
        id: "cp-011",
        title: "飲品券 -10",
        type: "amount_off",
        amountOff: 10,
        minSpend: 0,
        stackable: true,
        expiresAt: "2026-12-31T23:59:59.000Z",
      },
    ],
  },
  {
    id: "mem-003",
    name: "黃先生",
    phone: "66778899",
    balance: 0,
    level: "普通",
    coupons: [
      {
        id: "cp-020",
        title: "滿80減15",
        type: "amount_off",
        amountOff: 15,
        minSpend: 80,
        stackable: false,
        expiresAt: "2026-12-31T23:59:59.000Z",
      },
    ],
  },
];
