import {
  BackofficeSyncJob,
  AccountPermissionGroup,
  AccountStore,
  AccountUser,
  PosBootstrap,
  DeviceConfig,
  PosLocalSettings,
} from "@/lib/types";

export const defaultAccountStores: AccountStore[] = [
  {
    id: "macau-store-a",
    name: "澳門店 A",
    active: true,
    code: "MO-A01",
    city: "澳門",
    sourceStoreId: "main-store-001",
    sourceActive: true,
    manualDeactivated: false,
    effectiveActive: true,
    syncStatus: "ok",
    lastSyncedAt: "2026-08-08T08:30:00.000Z",
    lastHeartbeatAt: "2026-08-08T08:28:00.000Z",
    createdAt: "2026-08-08T00:00:00.000Z",
    updatedAt: "2026-08-08T00:00:00.000Z",
    note: "預設主門店。",
  },
  {
    id: "macau-store-b",
    name: "澳門店 B",
    active: true,
    code: "MO-B02",
    city: "澳門",
    sourceStoreId: "main-store-002",
    sourceActive: true,
    manualDeactivated: false,
    effectiveActive: true,
    syncStatus: "pending",
    lastSyncedAt: "2026-08-08T07:50:00.000Z",
    lastHeartbeatAt: "2026-08-08T07:20:00.000Z",
    createdAt: "2026-08-08T00:00:00.000Z",
    updatedAt: "2026-08-08T00:00:00.000Z",
    note: "分店示例。",
  },
];

export const defaultPermissionGroups: AccountPermissionGroup[] = [
  {
    id: "perm-admin",
    code: "admin-full",
    name: "管理員全權",
    role: "admin",
    permissions: { refundOrder: true, voidItem: true, manageAccounts: true },
    createdAt: "2026-08-08T00:00:00.000Z",
    updatedAt: "2026-08-08T00:00:00.000Z",
    note: "可管理帳戶、退款、退菜。",
  },
  {
    id: "perm-manager",
    code: "store-manager",
    name: "店長權限",
    role: "manager",
    permissions: { refundOrder: true, voidItem: true, manageAccounts: false },
    createdAt: "2026-08-08T00:00:00.000Z",
    updatedAt: "2026-08-08T00:00:00.000Z",
    note: "可退款、退菜，不可管理帳戶。",
  },
  {
    id: "perm-cashier",
    code: "cashier-basic",
    name: "收銀權限",
    role: "cashier",
    permissions: { refundOrder: false, voidItem: false, manageAccounts: false },
    createdAt: "2026-08-08T00:00:00.000Z",
    updatedAt: "2026-08-08T00:00:00.000Z",
    note: "基本收銀權限。",
  },
];

export const defaultAccountUsers: AccountUser[] = [
  {
    id: "acct-admin-1",
    account: "60000000",
    pin: "0000",
    name: "系統管理員",
    role: "admin",
    active: true,
    sourceAccountId: "main-account-001",
    sourceActive: true,
    manualDeactivated: false,
    effectiveActive: true,
    lastSyncedAt: "2026-08-08T08:30:00.000Z",
    storeIds: ["macau-store-a", "macau-store-b"],
    permissionGroupId: "perm-admin",
    permissions: {
      refundOrder: true,
      voidItem: true,
      manageAccounts: true,
    },
    createdAt: "2026-08-08T00:00:00.000Z",
    updatedAt: "2026-08-08T00:00:00.000Z",
    note: "總管理帳戶，可管理所有帳戶狀態。",
  },
  {
    id: "acct-manager-1",
    account: "63936541",
    pin: "1234",
    name: "店長",
    role: "manager",
    active: true,
    sourceAccountId: "main-account-101",
    sourceActive: true,
    manualDeactivated: false,
    effectiveActive: true,
    lastSyncedAt: "2026-08-08T08:25:00.000Z",
    storeIds: ["macau-store-a"],
    permissionGroupId: "perm-manager",
    permissions: {
      refundOrder: true,
      voidItem: true,
      manageAccounts: false,
    },
    createdAt: "2026-08-08T00:00:00.000Z",
    updatedAt: "2026-08-08T00:00:00.000Z",
    note: "門店管理帳戶。",
  },
  {
    id: "acct-cashier-1",
    account: "63936542",
    pin: "1234",
    name: "收銀員",
    role: "cashier",
    active: true,
    sourceAccountId: "main-account-201",
    sourceActive: true,
    manualDeactivated: false,
    effectiveActive: true,
    lastSyncedAt: "2026-08-08T08:25:00.000Z",
    storeIds: ["macau-store-a"],
    permissionGroupId: "perm-cashier",
    permissions: {
      refundOrder: false,
      voidItem: false,
      manageAccounts: false,
    },
    createdAt: "2026-08-08T00:00:00.000Z",
    updatedAt: "2026-08-08T00:00:00.000Z",
    note: "前台收銀帳戶。",
  },
];

export const defaultBackofficeSyncJobs: BackofficeSyncJob[] = [
  {
    id: "sync-full-001",
    jobType: "full",
    scope: "全部店舖",
    status: "success",
    startedAt: "2026-08-08T08:20:00.000Z",
    finishedAt: "2026-08-08T08:22:00.000Z",
    pulledCount: 18,
    upsertedCount: 18,
    failedCount: 0,
    summary: "主系統主檔同步完成，stores / accounts / bindings 已更新。",
  },
  {
    id: "sync-stores-002",
    jobType: "stores",
    scope: "澳門區門店",
    status: "running",
    startedAt: "2026-08-08T08:40:00.000Z",
    pulledCount: 2,
    upsertedCount: 1,
    failedCount: 0,
    summary: "門店同步進行中，等待主系統回傳剩餘門店資料。",
  },
  {
    id: "sync-accounts-003",
    jobType: "accounts",
    scope: "全部帳戶",
    status: "failed",
    startedAt: "2026-08-08T07:15:00.000Z",
    finishedAt: "2026-08-08T07:16:00.000Z",
    pulledCount: 12,
    upsertedCount: 10,
    failedCount: 2,
    summary: "帳戶同步中斷，有 2 筆資料格式不符合預期。",
    error: "主系統回傳的 permission_group_code 缺失。",
  },
];

export const mockBootstrap: PosBootstrap = {
  sourceVersion: 1,
  storeId: "macau-store-a",
  storeName: "澳門店 A",
  // 店家電話（收據抬頭，仿 57.doc「電話：xxx」一欄）。
  //
  // ⚠️ 刻意**唔填**：mock bootstrap 係 fallback，呢度一填就會永遠壓住
  // `resolveStoreTel()` 嘅「商家登入號碼」fallback，搞到所有舖都印同一個假號碼。
  // 收據電話嘅單一真源係 `src/lib/pos/store-tel.ts`：
  //   bootstrap.storeTel（將來 `pos_stores.tel`）→ 商家登入號碼 → 唔顯示。
  currency: "MOP",
  categories: [
    { id: "cat-rice", name: "飯類" },
    { id: "cat-noodle", name: "粉麵" },
    { id: "cat-drink", name: "飲品" },
  ],
  menuItems: [
    {
      id: "item-bbq-rice",
      categoryId: "cat-rice",
      name: "叉燒飯",
      price: 48,
      printerGroup: "kitchen",
    },
    {
      id: "item-beef-noodle",
      categoryId: "cat-noodle",
      name: "牛腩麵",
      price: 52,
      printerGroup: "kitchen",
    },
    {
      id: "item-fish-pot",
      categoryId: "cat-rice",
      name: "酸菜魚",
      price: 138,
      printerGroup: "kitchen",
      specGroups: [
        {
          id: "spice",
          name: "辣度",
          selectionMode: "single",
          required: true,
          options: [
            { id: "mild", label: "小辣", priceDelta: 0 },
            { id: "medium", label: "中辣", priceDelta: 0 },
            { id: "hot", label: "大辣", priceDelta: 0 },
          ],
        },
        {
          id: "size",
          name: "份量",
          selectionMode: "single",
          required: true,
          options: [
            { id: "small", label: "小份", priceDelta: 0 },
            { id: "large", label: "大份", priceDelta: 20 },
          ],
        },
        {
          id: "addon",
          name: "配菜",
          selectionMode: "multi",
          required: false,
          options: [
            { id: "regular", label: "標準", priceDelta: 0 },
            { id: "tofu", label: "加豆腐", priceDelta: 8 },
            { id: "vermicelli", label: "加粉絲", priceDelta: 10 },
          ],
        },
      ],
    },
    {
      id: "item-toast",
      categoryId: "cat-rice",
      name: "餐蛋治",
      price: 28,
      printerGroup: "kitchen",
    },
    {
      id: "item-lemon-tea",
      categoryId: "cat-drink",
      name: "凍檸茶",
      price: 18,
      printerGroup: "drinks",
    },
    {
      id: "item-milk-tea",
      categoryId: "cat-drink",
      name: "凍奶茶",
      price: 20,
      printerGroup: "drinks",
    },
  ],
  tables: [
    { id: "table-a01", name: "A01", area: "1樓", floorId: "floor-1" },
    { id: "table-a02", name: "A02", area: "1樓", floorId: "floor-1" },
    { id: "table-b01", name: "B01", area: "1樓", floorId: "floor-1" },
    { id: "table-b02", name: "B02", area: "2樓", floorId: "floor-2" },
  ],
  rules: {
    orderFlow: "send_then_pay",
    allowSplitBill: false,
    allowMemberLookup: false,
    taxRate: 0,
    serviceChargeRate: 0,
    paymentMethods: ["cash", "card", "mpay"],
  },
  printerGroups: ["kitchen", "drinks", "receipt"],
  lastUpdatedAt: "2026-08-04T00:00:00.000Z",
};

export const defaultDeviceConfig: DeviceConfig = {
  deviceId: "tablet-01",
  terminalName: "收銀機 01",
  storeId: "macau-store-a",
  updatedAt: "2026-08-04T00:00:00.000Z",
  printers: [
    {
      id: "printer-kitchen-1",
      role: "zone",
      zoneId: "kitchen",
      connectionType: "lan",
      name: "廚房打印機",
      model: "EPSON TM-U220",
      paperSize: "80mm",
      ipAddress: "192.168.1.110",
      enabled: true,
    },
    {
      id: "printer-drinks-1",
      role: "zone",
      zoneId: "drinks",
      connectionType: "lan",
      name: "吧台打印機",
      model: "EPSON TM-T82X",
      paperSize: "80mm",
      ipAddress: "192.168.1.111",
      enabled: true,
    },
    {
      id: "printer-receipt-1",
      role: "receipt",
      connectionType: "lan",
      name: "收據打印機",
      model: "EPSON TM-T82X",
      paperSize: "80mm",
      ipAddress: "192.168.1.112",
      enabled: true,
    },
    {
      id: "printer-label-1",
      role: "label",
      zoneId: "drinks",
      connectionType: "lan",
      name: "杯貼標籤機",
      model: "Brother QL-820NWB",
      paperSize: "62mm",
      ipAddress: "192.168.1.113",
      enabled: false,
    },
  ],
};

export const defaultPosLocalSettings: PosLocalSettings = {
  floors: [
    {
      id: "floor-1",
      name: "1樓",
      tables: [
        { id: "table-a01", name: "A01", area: "1樓", floorId: "floor-1" },
        { id: "table-a02", name: "A02", area: "1樓", floorId: "floor-1" },
        { id: "table-a03", name: "A03", area: "1樓", floorId: "floor-1" },
      ],
    },
    {
      id: "floor-2",
      name: "2樓",
      tables: [
        { id: "table-b01", name: "B01", area: "2樓", floorId: "floor-2" },
        { id: "table-b02", name: "B02", area: "2樓", floorId: "floor-2" },
      ],
    },
  ],
  paymentMethods: ["現金", "Mpay", "中銀"],
  menuPrinterOverrides: {
    "item-bbq-rice": "kitchen",
    "item-beef-noodle": "kitchen",
    "item-fish-pot": "kitchen",
    "item-toast": "kitchen",
    "item-lemon-tea": "drinks",
    "item-milk-tea": "drinks",
  },
  printZones: [
    { id: "kitchen", name: "廚房" },
    { id: "drinks", name: "水吧" },
  ],
  specTemplates: [
    {
      id: "tpl-drink-default",
      name: "飲品通用規格",
      specGroups: [
        {
          id: "drink-size",
          name: "杯型",
          selectionMode: "single",
          required: true,
          options: [
            { id: "regular", label: "標準", priceDelta: 0 },
            { id: "large", label: "大杯", priceDelta: 2 },
          ],
        },
        {
          id: "drink-ice",
          name: "冰量",
          selectionMode: "single",
          required: true,
          options: [
            { id: "normal-ice", label: "正常冰", priceDelta: 0 },
            { id: "less-ice", label: "少冰", priceDelta: 0 },
            { id: "no-ice", label: "走冰", priceDelta: 0 },
          ],
        },
        {
          id: "drink-sugar",
          name: "甜度",
          selectionMode: "single",
          required: true,
          options: [
            { id: "full-sugar", label: "正常甜", priceDelta: 0 },
            { id: "half-sugar", label: "半糖", priceDelta: 0 },
            { id: "less-sugar", label: "少甜", priceDelta: 0 },
            { id: "no-sugar", label: "走甜", priceDelta: 0 },
          ],
        },
      ],
    },
  ],
  printTemplates: {
    receipt: {
      blocks: {
        store_name: { visible: true, size: "m", bold: true, align: "center" },
        store_tel: { visible: true, size: "s", bold: false, align: "center" },
        order_no: { visible: true, size: "s", bold: false, align: "left" },
        table_name: { visible: true, size: "s", bold: false, align: "left" },
        order_time: { visible: true, size: "s", bold: false, align: "left" },
        checkout_time: { visible: true, size: "s", bold: false, align: "left" },
        server: { visible: false, size: "s", bold: false, align: "left" },
        items: { visible: true, size: "m", bold: true, align: "left" },
        discount_breakdown: { visible: true, size: "s", bold: false, align: "left" },
        subtotal_before_discount: { visible: true, size: "s", bold: false, align: "right" },
        service_charge_amount: { visible: true, size: "s", bold: false, align: "right" },
        tax_amount: { visible: true, size: "s", bold: false, align: "right" },
        rounding_amount: { visible: true, size: "s", bold: false, align: "right" },
        discount_amount: { visible: true, size: "s", bold: false, align: "right" },
        total: { visible: true, size: "l", bold: true, align: "right" },
        cash_tendered: { visible: true, size: "s", bold: false, align: "right" },
        change_amount: { visible: true, size: "s", bold: false, align: "right" },
        payment_method: { visible: true, size: "s", bold: false, align: "left" },
        order_note: { visible: true, size: "s", bold: false, align: "left" },
        footer: { visible: true, size: "s", bold: false, align: "center" },
      },
      order: ["store_name", "store_tel", "order_no", "table_name", "order_time", "checkout_time", "server", "items", "discount_breakdown", "subtotal_before_discount", "service_charge_amount", "tax_amount", "rounding_amount", "discount_amount", "total", "cash_tendered", "change_amount", "payment_method", "order_note", "footer"],
      footerText: "多謝惠顧，歡迎再次光臨",
    },
    label: {
      blocks: {
        header: { visible: true, size: "m", bold: true, align: "center" },
        item_name: { visible: true, size: "l", bold: true, align: "left" },
        temperature: { visible: true, size: "s", bold: false, align: "center" },
        cup_type: { visible: true, size: "s", bold: false, align: "center" },
        sugar: { visible: true, size: "s", bold: false, align: "center" },
        ice: { visible: true, size: "s", bold: false, align: "center" },
        sugar_tag: { visible: true, size: "s", bold: true, align: "center" },
        ice_tag: { visible: true, size: "s", bold: true, align: "center" },
        addons: { visible: true, size: "s", bold: false, align: "left" },
        specs: { visible: true, size: "s", bold: false, align: "left" },
        item_note: { visible: true, size: "s", bold: false, align: "left" },
        order_no: { visible: true, size: "s", bold: false, align: "center" },
        footer: { visible: true, size: "s", bold: false, align: "center" },
      },
      order: ["header", "item_name", "temperature", "cup_type", "sugar", "ice", "sugar_tag", "ice_tag", "addons", "specs", "item_note", "order_no", "footer"],
      headerText: "飲品標籤",
      footerText: "請盡快出品",
    },
    kitchen: {
      blocks: {
        store_name: { visible: true, size: "m", bold: true, align: "center" },
        order_no: { visible: true, size: "s", bold: false, align: "left" },
        table_name: { visible: true, size: "s", bold: false, align: "left" },
        order_type: { visible: true, size: "s", bold: true, align: "left" },
        time: { visible: true, size: "s", bold: false, align: "left" },
        server: { visible: false, size: "s", bold: false, align: "left" },
        items: { visible: true, size: "m", bold: true, align: "left" },
        customer_count: { visible: false, size: "s", bold: false, align: "left" },
        order_note: { visible: true, size: "s", bold: false, align: "left" },
        footer: { visible: true, size: "s", bold: false, align: "center" },
      },
      order: ["store_name", "order_no", "table_name", "order_type", "time", "server", "items", "customer_count", "order_note", "footer"],
      headerText: "",
      footerText: "廚房留底",
    },
    // 自助點餐機模版（第四個槽位）：預設內容同收據一致（規格 8）。
    // 商家可喺「打印」頁第四個分頁自行改，唔影響收銀台收據。
    kiosk: {
      blocks: {
        store_name: { visible: true, size: "m", bold: true, align: "center" },
        store_tel: { visible: true, size: "s", bold: false, align: "center" },
        order_no: { visible: true, size: "s", bold: false, align: "left" },
        table_name: { visible: true, size: "s", bold: false, align: "left" },
        order_time: { visible: true, size: "s", bold: false, align: "left" },
        checkout_time: { visible: false, size: "s", bold: false, align: "left" },
        server: { visible: false, size: "s", bold: false, align: "left" },
        items: { visible: true, size: "m", bold: true, align: "left" },
        discount_breakdown: { visible: true, size: "s", bold: false, align: "left" },
        subtotal_before_discount: { visible: true, size: "s", bold: false, align: "right" },
        service_charge_amount: { visible: true, size: "s", bold: false, align: "right" },
        tax_amount: { visible: true, size: "s", bold: false, align: "right" },
        rounding_amount: { visible: true, size: "s", bold: false, align: "right" },
        discount_amount: { visible: true, size: "s", bold: false, align: "right" },
        total: { visible: true, size: "l", bold: true, align: "right" },
        cash_tendered: { visible: true, size: "s", bold: false, align: "right" },
        change_amount: { visible: true, size: "s", bold: false, align: "right" },
        payment_method: { visible: true, size: "s", bold: false, align: "left" },
        order_note: { visible: true, size: "s", bold: false, align: "left" },
        footer: { visible: true, size: "s", bold: false, align: "center" },
      },
      order: ["store_name", "store_tel", "order_no", "table_name", "order_time", "checkout_time", "server", "items", "discount_breakdown", "subtotal_before_discount", "service_charge_amount", "tax_amount", "rounding_amount", "discount_amount", "total", "cash_tendered", "change_amount", "payment_method", "order_note", "footer"],
      footerText: "多謝惠顧，歡迎再次光臨",
    },
  },
  notePresets: ["多飯", "少飯", "小冰", "少冰", "走冰", "少甜", "走甜", "走蔥", "走辣"],
  cancelNotePresets: ["客人取消", "售罄", "下錯單", "重開一單"],
  // 免單備註：結帳頁撳「免單」時要揀嘅原因（設置 → 備註 → 免單備註 可增刪）
  compNotePresets: ["老闆請客", "員工餐", "客人投訴補償", "試食推廣", "熟客優惠"],
  discounts: [
    { id: "disc-90", label: "9折", rate: 90 },
    { id: "disc-85", label: "85折", rate: 85 },
    { id: "disc-80", label: "8折", rate: 80 },
    { id: "disc-50", label: "5折", rate: 50 },
  ],
  reopenReasons: ["結帳錯誤", "加錯項目", "折扣計錯", "找錯錢", "會員扣錯", "客人要求改單"],
  fullVoidBehavior: "cancelled",
  onlineOrderSettings: {
    autoAccept: false,
  },
  // 「自動接自助單」開關（取代 kioskKitchenMode）。true = 免確認直接出單（規格 5 嘅預設）。
  autoAcceptSelfOrder: true,
};
